CREATE TABLE EMPRESA (
    EmpresaId      INT IDENTITY(1,1) PRIMARY KEY,
    Nombre         NVARCHAR(150) NOT NULL,
    RUC_NIT        NVARCHAR(50)  NOT NULL,
    Estado         NVARCHAR(20)  NOT NULL DEFAULT 'ACTIVA',
    FechaCreacion  DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_EMPRESA_RUC_NIT UNIQUE (RUC_NIT)
);

CREATE TABLE USUARIO (
    UsuarioId      INT IDENTITY(1,1) PRIMARY KEY,
    EmpresaId      INT NULL,
    Nombre         NVARCHAR(150) NOT NULL,
    Email          NVARCHAR(200) NOT NULL,
    PasswordHash   NVARCHAR(255) NOT NULL,
    Estado         NVARCHAR(20)  NOT NULL DEFAULT 'ACTIVO',
    FechaCreacion  DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (Email),
    CONSTRAINT FK_USUARIO_EMPRESA FOREIGN KEY (EmpresaId) REFERENCES EMPRESA (EmpresaId)
);

CREATE INDEX IX_USUARIO_EMPRESA ON USUARIO (EmpresaId);
