CREATE TABLE GRUPO_DISPOSITIVO (
    GrupoDispositivoId INT IDENTITY(1,1) PRIMARY KEY,
    EmpresaId          INT NOT NULL,
    Nombre             NVARCHAR(150) NOT NULL,
    CONSTRAINT FK_GRUPODISPOSITIVO_EMPRESA FOREIGN KEY (EmpresaId) REFERENCES EMPRESA (EmpresaId),
    CONSTRAINT UQ_GRUPODISPOSITIVO_EMPRESA_NOMBRE UNIQUE (EmpresaId, Nombre)
);

CREATE TABLE DISPOSITIVO (
    DispositivoId      INT IDENTITY(1,1) PRIMARY KEY,
    EmpresaId          INT NOT NULL,
    GrupoDispositivoId INT NULL,
    IMEI               NVARCHAR(50) NOT NULL,
    NumeroSerie        NVARCHAR(100) NULL,
    Modelo             NVARCHAR(100) NULL,
    VersionAndroid     NVARCHAR(20) NULL,
    TokenEnrollment    NVARCHAR(255) NULL,
    Estado             NVARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
    UltimaConexion     DATETIME2 NULL,
    FechaRegistro      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_DISPOSITIVO_IMEI UNIQUE (IMEI),
    CONSTRAINT FK_DISPOSITIVO_EMPRESA FOREIGN KEY (EmpresaId) REFERENCES EMPRESA (EmpresaId),
    CONSTRAINT FK_DISPOSITIVO_GRUPO FOREIGN KEY (GrupoDispositivoId) REFERENCES GRUPO_DISPOSITIVO (GrupoDispositivoId)
);

CREATE INDEX IX_DISPOSITIVO_EMPRESA_ESTADO ON DISPOSITIVO (EmpresaId, Estado);

CREATE TABLE EVENTO_DISPOSITIVO (
    EventoDispositivoId BIGINT IDENTITY(1,1) PRIMARY KEY,
    DispositivoId        INT NOT NULL,
    Tipo                  NVARCHAR(30) NOT NULL,
    ValorJson             NVARCHAR(MAX) NULL,
    FechaEvento           DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_EVENTODISPOSITIVO_DISPOSITIVO FOREIGN KEY (DispositivoId) REFERENCES DISPOSITIVO (DispositivoId)
);

CREATE INDEX IX_EVENTODISPOSITIVO_DISPOSITIVO_FECHA ON EVENTO_DISPOSITIVO (DispositivoId, FechaEvento DESC);
