CREATE TABLE POLITICA (
    PoliticaId          INT IDENTITY(1,1) PRIMARY KEY,
    EmpresaId           INT NOT NULL,
    Nombre               NVARCHAR(150) NOT NULL,
    Tipo                  NVARCHAR(30) NOT NULL,
    ConfiguracionJson     NVARCHAR(MAX) NOT NULL,
    Cifrada               BIT NOT NULL DEFAULT 0,
    FechaActualizacion    DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_POLITICA_EMPRESA FOREIGN KEY (EmpresaId) REFERENCES EMPRESA (EmpresaId),
    CONSTRAINT UQ_POLITICA_EMPRESA_NOMBRE UNIQUE (EmpresaId, Nombre)
);

CREATE TABLE ASIGNACION_POLITICA (
    AsignacionPoliticaId INT IDENTITY(1,1) PRIMARY KEY,
    PoliticaId            INT NOT NULL,
    DispositivoId          INT NULL,
    GrupoDispositivoId      INT NULL,
    FechaAsignacion          DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ASIGNACIONPOLITICA_POLITICA FOREIGN KEY (PoliticaId) REFERENCES POLITICA (PoliticaId),
    CONSTRAINT FK_ASIGNACIONPOLITICA_DISPOSITIVO FOREIGN KEY (DispositivoId) REFERENCES DISPOSITIVO (DispositivoId),
    CONSTRAINT FK_ASIGNACIONPOLITICA_GRUPO FOREIGN KEY (GrupoDispositivoId) REFERENCES GRUPO_DISPOSITIVO (GrupoDispositivoId),
    CONSTRAINT CK_ASIGNACIONPOLITICA_TARGET CHECK (
        (DispositivoId IS NOT NULL AND GrupoDispositivoId IS NULL) OR
        (DispositivoId IS NULL AND GrupoDispositivoId IS NOT NULL)
    )
);

CREATE INDEX IX_ASIGNACIONPOLITICA_DISPOSITIVO ON ASIGNACION_POLITICA (DispositivoId);
CREATE INDEX IX_ASIGNACIONPOLITICA_GRUPO ON ASIGNACION_POLITICA (GrupoDispositivoId);
