CREATE TABLE APLICACION (
    AplicacionId    INT IDENTITY(1,1) PRIMARY KEY,
    EmpresaId        INT NOT NULL,
    Nombre            NVARCHAR(150) NOT NULL,
    PackageName        NVARCHAR(150) NOT NULL,
    VersionActual       NVARCHAR(30) NOT NULL,
    UrlArchivo           NVARCHAR(500) NOT NULL,
    FechaSubida            DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_APLICACION_EMPRESA FOREIGN KEY (EmpresaId) REFERENCES EMPRESA (EmpresaId),
    CONSTRAINT UQ_APLICACION_EMPRESA_PACKAGE UNIQUE (EmpresaId, PackageName)
);

CREATE TABLE DISPOSITIVO_APLICACION (
    DispositivoAplicacionId INT IDENTITY(1,1) PRIMARY KEY,
    DispositivoId             INT NOT NULL,
    AplicacionId               INT NOT NULL,
    VersionInstalada             NVARCHAR(30) NULL,
    Estado                        NVARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    FechaActualizacion              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DISPOSITIVOAPLICACION_DISPOSITIVO FOREIGN KEY (DispositivoId) REFERENCES DISPOSITIVO (DispositivoId),
    CONSTRAINT FK_DISPOSITIVOAPLICACION_APLICACION FOREIGN KEY (AplicacionId) REFERENCES APLICACION (AplicacionId),
    CONSTRAINT UQ_DISPOSITIVOAPLICACION_DISPOSITIVO_APP UNIQUE (DispositivoId, AplicacionId)
);

CREATE INDEX IX_DISPOSITIVOAPLICACION_APLICACION ON DISPOSITIVO_APLICACION (AplicacionId);
